# Generated by Django 4.2.4 on 2023-09-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_myuser_is_active_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
