# Generated by Django 4.2.4 on 2023-09-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notice_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
